'use strict';
const $=s=>document.querySelector(s);
const labels={accident:'To‘qnashuv',near_miss:'Xavfli yaqinlashuv',red_light:'Qizil chiroqda o‘tish',wrong_way:'Qarama-qarshi yurish',illegal_u_turn:'Taqiqlangan qayrilish',stopped_vehicle:'To‘xtagan transport',jaywalking:'O‘tish joyidan tashqari piyoda',failure_to_yield:'Piyodaga yo‘l bermaslik',illegal_turn:'Taqiqlangan burilish',solid_line_crossing:'Uzluksiz chiziqdan o‘tish',stop_line:'Stop-chiziq buzilishi',congestion:'Tirbandlik',road_obstacle:'Yo‘ldagi to‘siq',fire_smoke:'Olov / tutun'};
const zoneNames={road:'Qatnov qismi',exclusions:'Qatnov emas',crossings:'Piyoda o‘tish joyi',queue_zones:'Navbat hududi',lanes:'Yo‘lak'};
const colors={road:'#00C2FF',exclusions:'#EF4444',crossings:'#22C55E',queue_zones:'#F59E0B',lanes:'#c2a5ff'};
let health,scene,videos=[],selected=null,result=null,jobId=null,pollTimer=null,activeJob=false,draft=[],directionDraft=null;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function time(s){s=Math.max(0,s||0);return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(Math.floor(s%60)).padStart(2,'0')}`;}
function toast(s,error=false){const el=$('#toast');el.textContent=s;el.classList.remove('hidden');el.classList.toggle('error',error);clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.add('hidden'),6000);}
async function api(url,options={}){let r=await fetch(url,options);if(!r.ok){let j=await r.json().catch(()=>({detail:`So‘rov xatosi (${r.status})`}));throw Error(typeof j.detail==='string'?j.detail:JSON.stringify(j.detail));}return r.json();}
function page(name){window.scrollTo(0,0);document.querySelectorAll('.page').forEach(p=>p.classList.toggle('hidden',p.id!==`page-${name}`));document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.page===name));if(name==='scene')initScene();if(name==='analysis'){resizeOverlay();drawChart();}}
document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>page(b.dataset.page));document.querySelectorAll('[data-goto]').forEach(b=>b.onclick=()=>page(b.dataset.goto));$('#configure').onclick=()=>page('scene');
async function init(){try{health=await api('/api/health');scene=health.scene;$('#modelState').textContent=health.ready?'YOLOX-S · tayyor':'Model topilmadi';$('#modelState').classList.toggle('ready',health.ready);$('#fps').value=String(scene.analysis_fps);updateCoverage();videos=await api('/api/videos');renderVideos();await refreshJobs();const initial=videos.find(v=>v.source==='provided_sample_excerpt'||v.source==='provided_sample');if(initial){await selectVideo(initial);const rows=await api('/api/jobs');const j=rows.find(j=>j.video_id===initial.id&&j.status==='done');if(j){jobId=j.id;await loadResult(j);}}}catch(e){toast(e.message,true);$('#modelState').textContent='Serverga ulanib bo‘lmadi';}}
function renderVideos(){let target=$('#videoList');if(!videos.length){target.innerHTML='<p class="muted">Hali video yuklanmagan.</p>';return;}target.innerHTML=videos.map(v=>`<button class="video-card ${selected?.id===v.id?'active':''}" data-id="${v.id}"><img src="/api/videos/${v.id}/poster" alt=""><span><strong>${esc(v.name)}</strong><small>${time(v.duration)} · ${v.width}×${v.height}</small></span></button>`).join('');target.querySelectorAll('button').forEach(b=>b.onclick=()=>selectVideo(videos.find(v=>v.id===b.dataset.id)));}
function resetResults(){result=null;$('#metricEvents').textContent='—';$('#metricTracks').textContent='—';$('#metricTime').textContent='—';$('#metricRatio').textContent='Ushbu kompyuterda';$('#resultWarnings').replaceChildren();$('#eventsList').replaceChildren();$('#timeline').innerHTML='<p class="muted">Tahlildan keyin hodisani bosib, videodagi vaqtiga o‘ting.</p>';$('#eventCount').textContent='Natija kutilmoqda';$('#downloadJson').classList.add('hidden');$('#heatmap').classList.add('hidden');$('#heatmapEmpty').classList.remove('hidden');$('#classFilter').innerHTML='<option value="all">Barcha sinflar</option>';drawChart();}
async function selectVideo(v){if(activeJob){toast('Avval joriy tahlilni tugating yoki bekor qiling.');return;}selected=v;resetResults();$('#jobProgress').classList.add('hidden');$('#videoName').textContent=v.name;$('#videoMeta').textContent=`${v.width}×${v.height} · ${v.fps.toFixed(2)} fps · ${time(v.duration)} · ${(v.bytes/1048576).toFixed(1)} MB`;$('#video').src=`/api/videos/${v.id}/media`;$('#video').poster=`/api/videos/${v.id}/poster`;$('#video').classList.remove('hidden');$('#overlay').classList.remove('hidden');$('#emptyStage').classList.add('hidden');$('#analyze').disabled=true;renderVideos();resizeOverlay();try{const d=await api(`/api/videos/${v.id}/scene`);if(selected?.id!==v.id)return;scene=d.scene;updateCoverage();$('#analyze').disabled=!health.ready;}catch(e){toast(e.message,true);}}
function upload(file){if(!file)return;if(activeJob)return toast('Avval joriy tahlilni tugating.',true);if(!file.name.toLowerCase().endsWith('.mp4'))return toast('Faqat MP4 fayl tanlang.',true);if(file.size>8192*1048576)return toast('Video hajmi 8 GB dan oshmasin.',true);const data=new FormData();data.append('file',file);const xhr=new XMLHttpRequest();xhr.open('POST','/api/videos');$('#uploadProgress').classList.remove('hidden');$('#analyze').disabled=true;xhr.upload.onprogress=e=>{if(e.lengthComputable){$('#uploadProgress progress').value=e.loaded/e.total*100;$('#uploadProgress small').textContent=`Yuklanmoqda… ${Math.round(e.loaded/e.total*100)}%`;}};xhr.onload=()=>{ $('#uploadProgress').classList.add('hidden');try{const r=JSON.parse(xhr.responseText);if(xhr.status>=400)throw Error(r.detail||'Yuklash xatosi');videos.unshift(r);selectVideo(r);toast('Video tayyor. Tahlilni boshlashingiz mumkin.');}catch(e){toast(e.message,true);$('#analyze').disabled=!selected||!health.ready;}};xhr.onerror=()=>{toast('Yuklashda ulanish uzildi.',true);$('#uploadProgress').classList.add('hidden');$('#analyze').disabled=!selected||!health.ready;};xhr.send(data);}
$('#fileInput').onchange=e=>{upload(e.target.files[0]);e.target.value='';};$('#drop').ondragover=e=>{e.preventDefault();$('#drop').classList.add('dragging');};$('#drop').ondragleave=()=>$('#drop').classList.remove('dragging');$('#drop').ondrop=e=>{e.preventDefault();$('#drop').classList.remove('dragging');upload(e.dataTransfer.files[0]);};
$('#analyze').onclick=async()=>{if(!selected)return;try{const conf={...scene,analysis_fps:Number($('#fps').value)};const j=await api('/api/jobs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({video_id:selected.id,scene:conf,team:$('#team').value.trim()||'unnamed-team'})});jobId=j.id;resetResults();setBusy(true);$('#jobProgress').classList.remove('hidden');poll();}catch(e){toast(e.message,true);}};
function setBusy(b){activeJob=b;document.body.classList.toggle('analyzing',b);$('#analyze').disabled=b||!selected||!health?.ready;$('#cancel').classList.toggle('hidden',!b);$('#fileInput').disabled=b;}
$('#cancel').onclick=async()=>{if(jobId){await api(`/api/jobs/${jobId}/cancel`,{method:'POST'}).catch(e=>toast(e.message,true));$('#cancel').disabled=true;}};
async function poll(){clearTimeout(pollTimer);try{const j=await api(`/api/jobs/${jobId}`);$('#progressMessage').textContent=j.message;$('#progressBar').value=j.progress;$('#progressValue').textContent=`${Math.round(j.progress*100)}%`;$('#progressStats').textContent=j.stats&&Number.isFinite(j.stats.frame)?`${j.stats.frame} kadr · ${j.stats.objects} iz · ${j.stats.elapsed} soniya`:'';if(['done','error','cancelled'].includes(j.status)){setBusy(false);$('#cancel').disabled=false;await refreshJobs();if(j.status==='done')await loadResult(j);else toast(j.message,j.status==='error');}else pollTimer=setTimeout(poll,700);}catch(e){setBusy(false);toast(e.message,true);}}
async function refreshJobs(){let rows=await api('/api/jobs');$('#jobList').innerHTML=rows.length?rows.slice(0,8).map(j=>`<button data-id="${j.id}">${esc(j.name)}<small>${esc(j.status==='done'?`${j.events} hodisa · tayyor`:j.message)}</small></button>`).join(''):'<span class="muted">Hali tahlil yo‘q</span>';$('#jobList').querySelectorAll('button').forEach(b=>b.onclick=async()=>{if(activeJob)return toast('Avval joriy tahlilni tugating.');const j=rows.find(x=>x.id===b.dataset.id);const v=videos.find(x=>x.id===j.video_id);if(v)selectVideo(v);jobId=j.id;if(j.status==='done')await loadResult(j);else if(['running','queued'].includes(j.status)){setBusy(true);$('#jobProgress').classList.remove('hidden');poll();}else toast(j.message,true);});}
async function loadResult(j){result=await api(`/api/jobs/${j.id}/result.json`);$('#metricEvents').textContent=result.events.length;$('#metricTracks').textContent=result.unique_tracks;$('#metricTime').textContent=`${result.runtime_sec.toFixed(1)}s`;$('#metricRatio').textContent=`Video davomiyligiga nisbatan ${result.runtime_ratio.toFixed(2)}×`;$('#resultWarnings').innerHTML=result.warnings.map(x=>`<div class="notice">${esc(x)}</div>`).join('');$('#downloadJson').href=`/api/jobs/${j.id}/predictions.json`;$('#downloadJson').classList.remove('hidden');$('#heatmap').src=`/api/jobs/${j.id}/heatmap.jpg`;$('#heatmap').classList.remove('hidden');$('#heatmapEmpty').classList.add('hidden');let cls=[...new Set(result.events.map(e=>e[2]))];$('#classFilter').innerHTML='<option value="all">Barcha sinflar</option>'+cls.map(c=>`<option value="${c}">${labels[c]}</option>`).join('');renderEvents();drawChart();drawOverlay();$('#chartNote').textContent=`${result.frames.length} tahlil kadri · har ${result.sample_stride}-kadr. Izlar soni qayta sanash xatolariga ega bo‘lishi mumkin.`;}
$('#classFilter').onchange=renderEvents;
function seek(t){$('#video').currentTime=t;$('#video').pause();drawOverlay();}
function renderEvents(){if(!result)return;const filter=$('#classFilter').value;let es=result.events.filter(e=>filter==='all'||e[2]===filter);$('#eventCount').textContent=`${es.length} segment`;if(!es.length){$('#timeline').innerHTML=`<p class="muted">${result.enabled_classes.length?'Faol qoidalar hodisa topmadi. Bu videoda hodisa yo‘qligini kafolatlamaydi.':'Sahna qoidalari faol emas. Zonalarni tasdiqlab, videoni qayta tahlil qiling.'}</p>`;$('#eventsList').replaceChildren();return;}let cs=[...new Set(es.map(e=>e[2]))];$('#timeline').innerHTML=cs.map(c=>`<div class="timeline-row"><span>${esc(c)}</span><div class="timeline-track">${es.filter(e=>e[2]===c).map(e=>`<button class="segment" data-time="${e[0]}" style="left:${e[0]/result.meta.duration*100}%;width:${(e[1]-e[0])/result.meta.duration*100}%" title="${esc(labels[c])} ${time(e[0])}–${time(e[1])}" aria-label="${esc(labels[c])}, ${time(e[0])}"></button>`).join('')}</div></div>`).join('')+`<div class="time-labels"><span>00:00</span><span>${time(result.meta.duration/2)}</span><span>${time(result.meta.duration)}</span></div>`;$('#eventsList').innerHTML=es.map(e=>`<div class="event-row"><span class="time">${time(e[0])}–${time(e[1])}</span><span>${esc(labels[e[2]])}<small>${esc(e[2])} · inson tekshiruvi kerak</small></span><button data-time="${e[0]}">Ko‘rish</button></div>`).join('');document.querySelectorAll('[data-time]').forEach(b=>b.onclick=()=>seek(Number(b.dataset.time)));}
function resizeOverlay(){const stage=$('#stage'),canvas=$('#overlay');canvas.width=stage.clientWidth;canvas.height=stage.clientHeight;drawOverlay();}
function drawOverlay(){const c=$('#overlay'),ctx=c.getContext('2d');ctx.clearRect(0,0,c.width,c.height);$('#playbackTime').textContent=time($('#video').currentTime);if(!result||!$('#showTracks').checked||!result.frames.length)return;const t=$('#video').currentTime;let lo=0,hi=result.frames.length-1;while(lo<hi){let mid=Math.ceil((lo+hi)/2);if(result.frames[mid].t<=t)lo=mid;else hi=mid-1;}const rec=result.frames[lo];if(Math.abs(rec.t-t)>Math.max(.8,result.sample_stride/result.meta.fps*1.5))return;const ratio=Math.min(c.width/result.meta.width,c.height/result.meta.height),w=result.meta.width*ratio,h=result.meta.height*ratio,x0=(c.width-w)/2,y0=(c.height-h)/2;for(const o of rec.objects){let color=o.label==='person'?'#22C55E':'#00C2FF';ctx.strokeStyle=color;ctx.lineWidth=1.5;const [a,b,d,e]=o.box;ctx.strokeRect(x0+a*w,y0+b*h,(d-a)*w,(e-b)*h);ctx.fillStyle=color;ctx.font='11px sans-serif';let tx=`${o.label} #${o.id}`;let tw=ctx.measureText(tx).width;ctx.fillRect(x0+a*w,y0+b*h-18,tw+8,18);ctx.fillStyle='#0B1220';ctx.fillText(tx,x0+a*w+4,y0+b*h-5);ctx.beginPath();o.trail.forEach((p,i)=>i?ctx.lineTo(x0+p[0]*w,y0+p[1]*h):ctx.moveTo(x0+p[0]*w,y0+p[1]*h));ctx.stroke();}}
$('#video').addEventListener('timeupdate',drawOverlay);$('#video').addEventListener('loadedmetadata',resizeOverlay);$('#video').addEventListener('error',()=>toast('Brauzer ushbu video kodekini ocholmadi. Server tahlili ishlashi mumkin; H.264 MP4 tavsiya etiladi.',true));$('#showTracks').onchange=drawOverlay;new ResizeObserver(resizeOverlay).observe($('#stage'));
function drawChart(){const c=$('#densityChart');if(!c.clientWidth)return;c.width=c.clientWidth*2;c.height=320;const ctx=c.getContext('2d'),w=c.width,h=c.height;ctx.clearRect(0,0,w,h);ctx.strokeStyle='#293447';ctx.lineWidth=1;for(let i=1;i<4;i++){ctx.beginPath();ctx.moveTo(32,h*i/4);ctx.lineTo(w-5,h*i/4);ctx.stroke();}if(!result?.series.length)return;let mx=result.series.reduce((m,r)=>Math.max(m,r.count),1);for(const [key,color] of [['vehicles','#00C2FF'],['people','#22C55E']]){ctx.strokeStyle=color;ctx.lineWidth=3;ctx.beginPath();result.series.forEach((r,i)=>{let x=32+(w-40)*r.t/result.meta.duration,y=h-25-r[key]/mx*(h-50);i?ctx.lineTo(x,y):ctx.moveTo(x,y);});ctx.stroke();}ctx.font='20px sans-serif';ctx.fillStyle='#98a9bf';ctx.fillText(String(mx),0,24);ctx.fillText('0',0,h-20);}
function updateCoverage(){if(!health||!scene)return;const enabled={stopped_vehicle:scene.verified&&scene.road.length&&scene.queue_zones_complete,jaywalking:scene.verified&&scene.road.length&&scene.crossings_complete,wrong_way:scene.verified&&scene.road.length&&scene.lanes.length,failure_to_yield:scene.verified&&scene.road.length&&scene.crossings.length,road_obstacle:scene.verified&&scene.road.length,congestion:scene.verified&&scene.road.length&&scene.lanes.length&&scene.lane_coverage_complete};$('#coverage').innerHTML=health.classes.map(c=>`<div class="coverage-row ${enabled[c]?'enabled':''}"><span>${esc(c)}<br><small class="muted">${esc(labels[c])}</small></span><span>${enabled[c]?'Dastlabki qoida faol':health.supported.includes(c)?'Sahna sozlamasi kerak':'Qo‘llab-quvvatlanmaydi'}</span></div>`).join('');const n=Object.values(enabled).filter(Boolean).length;$('#sceneHint').textContent=n?`${n} ta hodisa qoidasi faol. Boshqa kameradan video bo‘lsa zonalarni qayta sozlang.`:'Sahna zonalari sozlanmaguncha faqat obyektlar tahlili ishlaydi.';}
function initScene(){if(!scene)return;$('#sceneTitle').textContent=selected?selected.name:'Avval Tahlil bo‘limida video tanlang';if(selected){$('#sceneImage').src=`/api/videos/${selected.id}/poster`;}$('#crossingsComplete').checked=scene.crossings_complete;$('#queuesComplete').checked=scene.queue_zones_complete;$('#lanesComplete').checked=scene.lane_coverage_complete;$('#sceneVerified').checked=scene.verified;renderZones();resizeScene();}
function resizeScene(){const img=$('#sceneImage'),c=$('#sceneCanvas');c.width=img.clientWidth;c.height=img.clientHeight;drawScene();}$('#sceneImage').onload=resizeScene;new ResizeObserver(resizeScene).observe($('.scene-stage'));
function drawScene(){const c=$('#sceneCanvas'),ctx=c.getContext('2d'),w=c.width,h=c.height;ctx.clearRect(0,0,w,h);if(!scene)return;function poly(points,color,closed=true){if(!points.length)return;ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(p[0]*w,p[1]*h):ctx.moveTo(p[0]*w,p[1]*h));if(closed)ctx.closePath();ctx.strokeStyle=color;ctx.lineWidth=2;ctx.stroke();if(closed){ctx.fillStyle=color+'28';ctx.fill();}points.forEach(p=>{ctx.beginPath();ctx.arc(p[0]*w,p[1]*h,3,0,Math.PI*2);ctx.fillStyle=color;ctx.fill();});}poly(scene.road,colors.road);for(const k of ['crossings','queue_zones','exclusions'])for(const p of scene[k])poly(p,colors[k]);for(const lane of scene.lanes){poly(lane.polygon,colors.lanes);let cx=lane.polygon.reduce((a,p)=>a+p[0],0)/lane.polygon.length,cy=lane.polygon.reduce((a,p)=>a+p[1],0)/lane.polygon.length;let d=lane.direction,len=Math.hypot(...d),dx=d[0]/len*.06,dy=d[1]/len*.06;arrow(ctx,[cx*w,cy*h],[(cx+dx)*w,(cy+dy)*h],colors.lanes);}poly(draft,colors[$('#zoneType').value],false);if(directionDraft){poly(directionDraft.polygon,colors.lanes);if(directionDraft.points.length){let p=directionDraft.points[0];ctx.fillStyle=colors.lanes;ctx.beginPath();ctx.arc(p[0]*w,p[1]*h,6,0,Math.PI*2);ctx.fill();}}$('#pointCount').textContent=directionDraft?`${directionDraft.points.length}/2 yo‘nalish nuqtasi`:`${draft.length} nuqta`;}
function arrow(ctx,a,b,color){ctx.strokeStyle=color;ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(...a);ctx.lineTo(...b);let ang=Math.atan2(b[1]-a[1],b[0]-a[0]);ctx.moveTo(b[0]-10*Math.cos(ang-.5),b[1]-10*Math.sin(ang-.5));ctx.lineTo(...b);ctx.lineTo(b[0]-10*Math.cos(ang+.5),b[1]-10*Math.sin(ang+.5));ctx.stroke();}
$('#sceneCanvas').onclick=e=>{if(!selected)return toast('Avval video tanlang.',true);const rect=e.currentTarget.getBoundingClientRect(),p=[(e.clientX-rect.left)/rect.width,(e.clientY-rect.top)/rect.height];if(directionDraft){directionDraft.points.push(p);if(directionDraft.points.length===2){let [a,b]=directionDraft.points,dir=[b[0]-a[0],b[1]-a[1]];if(Math.hypot(...dir)<.01){directionDraft.points=[];return toast('Yo‘nalish nuqtalari uzoqroq bo‘lsin.',true);}scene.lanes.push({polygon:directionDraft.polygon,direction:dir,group:$('#laneGroup').value||'1',name:`Yo‘lak ${scene.lanes.length+1}`});directionDraft=null;invalidateScene();renderZones();toast('Yo‘lak va yo‘nalish qo‘shildi.');}}else{if(draft.length>=80)return toast('Bir zonada 80 nuqtagacha mumkin.',true);draft.push(p);}drawScene();};
function invalidateScene(){scene.verified=false;$('#sceneVerified').checked=false;$('#sceneStatus').textContent='Saqlanmagan o‘zgarishlar';updateCoverage();}
$('#finishZone').onclick=()=>{if(directionDraft)return toast('Kadrga yo‘nalishning bosh va oxirini bosing.');if(draft.length<3)return toast('Kamida 3 nuqta belgilang.',true);let key=$('#zoneType').value;if(key==='lanes'){directionDraft={polygon:draft,points:[]};draft=[];toast('Endi ruxsat etilgan harakat yo‘nalishining bosh va oxirini bosing.');}else{if(key==='road')scene.road=draft;else scene[key].push(draft);draft=[];invalidateScene();renderZones();}drawScene();};
$('#undoPoint').onclick=()=>{if(directionDraft)directionDraft.points.pop();else draft.pop();drawScene();};$('#clearDraft').onclick=()=>{draft=[];directionDraft=null;drawScene();};$('#zoneType').onchange=()=>{draft=[];directionDraft=null;$('#laneGroupLabel').classList.toggle('hidden',$('#zoneType').value!=='lanes');drawScene();};
function renderZones(){let rows=[];if(scene.road.length)rows.push({key:'road',i:0,text:zoneNames.road});for(const key of ['crossings','queue_zones','exclusions','lanes'])scene[key].forEach((v,i)=>rows.push({key,i,text:`${zoneNames[key]} ${i+1}${key==='lanes'?` · guruh ${v.group}`:''}`}));$('#zoneList').innerHTML=rows.map(r=>`<div class="zone-item"><span>${esc(r.text)}</span><button data-key="${r.key}" data-index="${r.i}" aria-label="${esc(r.text)}ni olib tashlash">Olish</button></div>`).join('');$('#zoneList').querySelectorAll('button').forEach(b=>b.onclick=()=>{if(b.dataset.key==='road')scene.road=[];else scene[b.dataset.key].splice(Number(b.dataset.index),1);invalidateScene();renderZones();drawScene();});}
function sceneFromControls(){return {...scene,crossings_complete:$('#crossingsComplete').checked,queue_zones_complete:$('#queuesComplete').checked,lane_coverage_complete:$('#lanesComplete').checked,verified:$('#sceneVerified').checked,analysis_fps:Number($('#fps').value)};}
$('#saveScene').onclick=async()=>{if(draft.length||directionDraft)return toast('Avval chizilayotgan zonani tugating yoki tozalang.',true);const next=sceneFromControls();if(next.verified&&!next.road.length)return toast('Tasdiqlash uchun qatnov qismini belgilang.',true);try{let r=await api(selected?`/api/videos/${selected.id}/scene`:'/api/scene',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(next)});scene=r.scene;updateCoverage();$('#sceneStatus').textContent='Saqlandi. Yangi tahlillarga qo‘llanadi.';toast('Sahna sozlamasi saqlandi.');}catch(e){toast(e.message,true);}};
function downloadObject(obj,name){const url=URL.createObjectURL(new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('#exportScene').onclick=()=>downloadObject(sceneFromControls(),'scene.json');$('#importScene').onchange=async e=>{let f=e.target.files[0];if(!f)return;try{const imported=JSON.parse(await f.text());imported.verified=false;let r=await api(selected?`/api/videos/${selected.id}/scene`:'/api/scene',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(imported)});scene=r.scene;draft=[];directionDraft=null;initScene();updateCoverage();toast('Import qilindi. Sahna mosligini tekshirib, tasdiqlang.');}catch(err){toast(err.message,true);}e.target.value='';};
window.addEventListener('resize',drawChart);init();
