'use strict';
// Camera controls, independent human review, and the published task specification.
const extraPages={camera:'Jonli kamera',review:'Hodisani tekshirish',project:'Nizom va jamoa'};
for(const [key,title] of Object.entries(extraPages)){
  const b=document.createElement('button');b.className='nav';b.dataset.page=key;b.textContent=title;
  b.onclick=()=>{page(key);if(key==='review')openReview().catch(e=>toast(e.message,true));if(key==='project')openProject().catch(e=>toast(e.message,true));};$('nav').append(b);
}
$('main').insertAdjacentHTML('beforeend',`
<section id="page-camera" class="page hidden"><div class="page-title"><div><p class="eyebrow">YUKSAVA · JONLI KUZATUV</p><h1>Kamera sizning boshqaruvingizda.</h1></div></div>
<div class="feature-grid"><div class="panel"><div class="section-head"><h2>Jonli ko‘rinish</h2><span id="cameraState" class="badge">O‘chirilgan</span></div><div class="camera-stage"><div class="camera-empty" id="cameraEmpty"><div class="radar"></div><span>Kamerani yoqing</span></div><video id="cameraVideo" autoplay muted playsinline></video><canvas id="cameraOverlay"></canvas></div><p id="cameraStats" class="status-line" aria-live="polite">Kamera faqat “Yoqish” bosilganda ochiladi.</p></div>
<aside class="panel feature-controls"><h2>Kamera boshqaruvi</h2><label>Qurilma<select id="cameraDevice"><option value="">Asosiy kamera</option></select></label><label>Aniqlik<select id="cameraResolution"><option value="1280">HD · 1280 × 720</option><option value="1920">Full HD · 1920 × 1080</option><option value="640">Tezkor · 640 × 360</option></select></label><button id="cameraStart" class="primary">Kamerani yoqish</button><button id="cameraStop" class="secondary" disabled>Kamerani o‘chirish</button><label class="switch"><input id="cameraDetect" type="checkbox" checked> Obyektlarni jonli aniqlash</label><p class="fine">Transport, piyoda va ayrim hayvonlar belgilanadi. Kamera kadrlari saqlanmaydi. Hodisalarning vaqt oralig‘i MP4 tahlilida hisoblanadi.</p><p class="fine">Kamera almashtirish yoki aniqlikni o‘zgartirish uchun o‘chirib, qayta yoqing. Kamera ruxsatini brauzer so‘raydi.</p></aside></div><p class="notice camera-notice">Bu bo‘lim siz ruxsat bergan kompyuter/USB kamerasi uchun. WIUT topshirig‘ida berilgan kameradan qo‘shimcha video yig‘ish taqiqlangan; tanlov tahlili berilgan MP4 fayllarda bajariladi.</p></section>
<section id="page-review" class="page hidden"><div class="page-title"><div><p class="eyebrow">14 SINF · VAQT CHEGARALARI</p><h1>Hodisani videoda tekshiring.</h1></div></div><p id="reviewTitle" class="status-line">Tahlil bo‘limida video tanlang.</p><div class="feature-grid"><div class="panel"><video id="reviewVideo" class="review-video" controls playsinline></video><div class="button-row"><button id="frameBack" class="secondary">← 1 kadr</button><button id="frameNext" class="secondary">1 kadr →</button><button id="markStart" class="secondary">Boshlanishni belgilash</button><button id="markEnd" class="secondary">Tugashni belgilash</button></div><div id="reviewRows"></div></div><aside class="panel feature-controls"><label>Hodisa sinfi<select id="reviewClass">${Object.entries(labels).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select></label><p id="boundaryHelp" class="fine"></p><label>Boshlanish (soniya)<input id="reviewStart" type="number" min="0" step="0.001" value="0"></label><label>Tugash (soniya)<input id="reviewEnd" type="number" min="0" step="0.001" value="1"></label><button id="addAnnotation" class="primary">Hodisani qo‘shish</button><label class="switch"><input id="reviewed" type="checkbox"> Butun videoni ko‘rib, barcha hodisalarni tekshirdim</label><button id="saveAnnotations" class="secondary">Annotatsiyani saqlash</button><button id="exportAnnotations" class="secondary">Annotatsiya JSON ↓</button><button id="scoreAnnotations" class="secondary">Modelni annotatsiya bilan baholash</button><p class="fine">Qo‘lda belgilangan hodisalar model natijasidan alohida saqlanadi. Bir sinfning ustma-ust segmentlari saqlashda birlashtiriladi. Tugamagan hodisaning oxiri video davomiyligiga teng.</p><p id="reviewStatus" class="status-line" aria-live="polite"></p></aside></div><pre id="reviewScore" class="hidden score-result"></pre></section>
<section id="page-project" class="page hidden"><div class="page-title"><div><p class="eyebrow">WIUT HACKATHON 2026</p><h1>Nizom, videolar va jamoa.</h1></div></div><div id="teamCards" class="team-cards"></div><div id="sampleGallery" class="sample-gallery"></div><div class="panel"><div class="section-head"><h2>Hodisa qachon boshlanadi va tugaydi?</h2><span class="badge">Avtomatik qamrov va qo‘lda tekshirish alohida</span></div><div class="table-scroll"><table class="spec-table"><thead><tr><th>Sinf</th><th>Boshlanish</th><th>Tugash</th><th>Avtomatik holat</th></tr></thead><tbody id="specRows"></tbody></table></div></div><div class="about-grid" style="margin-top:24px"><article class="panel"><h2>Baholash va chegaralar</h2><p>Part A: 0.3 / 0.5 / 0.7 vaqt kesishuvlaridagi macro F1. Model: 0.7 A + 0.3 B; testda accident bo‘lmasa M=A. Yakuniy eliminatsiya: 60% model, 25% sayt, 15% kod.</p><p>T4 sinfidagi 16 GB GPU, 8 CPU, 32 GB RAM. Python ≥3.10, og‘irliklar ≤5 GB. A+B ishlash vaqti ≤3× video. Inference offline; Part B faqat joriy va o‘tgan kadrlarni ko‘radi.</p><p id="cameraDocState"></p><p><a href="/api/documents/task" target="_blank" rel="noopener">Asl nizom PDF ↗</a> · <a href="/api/documents/report" target="_blank" rel="noopener">Texnik hisobot ↓</a></p><p class="fine">Qoida mavjudligi aniqlik kafolati emas. Part B hozir ruxsat etilgan nol baseline. T4 va hidden test natijalari mavjud emas.</p></article><article class="panel feature-controls"><h2>Jamoa va topshirish havolalari</h2><label>Jamoa nomi<input id="projectTeam" type="text" maxlength="100"></label><div id="memberForms"></div><label>Public repository<input id="projectRepo" type="url" placeholder="https://github.com/…"></label><label>Commit yoki tag<input id="projectRevision" type="text"></label><label>Public sayt<input id="projectWebsite" type="url" placeholder="https://…"></label><label>Og‘irliklar havolasi<input id="projectWeights" type="url" placeholder="https://…"></label><button id="saveProject" class="primary">Ma’lumotlarni saqlash</button><p class="fine">Saqlash saytni internetga chiqarmaydi. Public havolalar va jamoaning haqiqiy ma’lumotlarini kiriting.</p><p id="projectStatus" class="status-line"></p></article></div></section>`);

let cameraStream=null,cameraTimer=null,cameraAbort=null,cameraEpoch=0;
function stopCamera(){cameraEpoch++;clearTimeout(cameraTimer);cameraAbort?.abort();cameraStream?.getTracks().forEach(t=>t.stop());cameraStream=null;$('#cameraVideo').srcObject=null;$('#cameraStop').disabled=true;$('#cameraStart').disabled=false;$('#cameraDevice').disabled=false;$('#cameraResolution').disabled=false;$('#cameraState').textContent='O‘chirilgan';$('#cameraEmpty').classList.remove('hidden');document.body.classList.remove('camera-on');const c=$('#cameraOverlay');c.getContext('2d').clearRect(0,0,c.width,c.height);$('#cameraStats').textContent='Kamera o‘chirildi.';}
$('#cameraStop').onclick=stopCamera;window.addEventListener('pagehide',stopCamera);
$('#cameraStart').onclick=async()=>{
  stopCamera();const epoch=cameraEpoch;$('#cameraStart').disabled=true;
  try{
    if(!navigator.mediaDevices?.getUserMedia)throw Error('Kamera uchun localhost yoki HTTPS va kamera ruxsati kerak.');
    const w=Number($('#cameraResolution').value),device=$('#cameraDevice').value;
    const stream=await navigator.mediaDevices.getUserMedia({video:{width:{ideal:w},height:{ideal:Math.round(w*9/16)},...(device?{deviceId:{exact:device}}:{})},audio:false});
    if(epoch!==cameraEpoch){stream.getTracks().forEach(t=>t.stop());return;}
    cameraStream=stream;$('#cameraVideo').srcObject=stream;await $('#cameraVideo').play();
    const devices=await navigator.mediaDevices.enumerateDevices();$('#cameraDevice').innerHTML=devices.filter(d=>d.kind==='videoinput').map((d,i)=>`<option value="${esc(d.deviceId)}">${esc(d.label||`Kamera ${i+1}`)}</option>`).join('');$('#cameraDevice').value=stream.getVideoTracks()[0].getSettings().deviceId||'';
    $('#cameraDevice').disabled=true;$('#cameraResolution').disabled=true;$('#cameraStop').disabled=false;$('#cameraEmpty').classList.add('hidden');$('#cameraState').textContent='Jonli';document.body.classList.add('camera-on');
    stream.getVideoTracks()[0].addEventListener('ended',()=>{stopCamera();toast('Kamera uzildi.',true);});cameraLoop(epoch);
  }catch(e){stopCamera();toast(e.name==='NotAllowedError'?'Brauzer yoki tizim kamera ruxsatini bermadi.':e.name==='NotFoundError'?'Ulangan kamera topilmadi.':e.message,true);}
};
async function cameraLoop(epoch){
  if(!cameraStream||epoch!==cameraEpoch)return;
  const v=$('#cameraVideo'),c=$('#cameraOverlay');c.width=v.videoWidth;c.height=v.videoHeight;const ctx=c.getContext('2d');
  try{
    if($('#cameraDetect').checked&&v.videoWidth){
      const frame=document.createElement('canvas');frame.width=640;frame.height=Math.round(v.videoHeight*640/v.videoWidth);frame.getContext('2d').drawImage(v,0,0,frame.width,frame.height);
      const blob=await new Promise(resolve=>frame.toBlob(resolve,'image/jpeg',.8));cameraAbort=new AbortController();
      const r=await api('/api/camera/frame',{method:'POST',headers:{'Content-Type':'image/jpeg'},body:blob,signal:cameraAbort.signal});
      if(epoch!==cameraEpoch)return;
      const xScale=c.width,yScale=c.height;ctx.lineWidth=Math.max(2,c.width/500);ctx.font=`${Math.max(16,c.width/65)}px sans-serif`;
      for(const o of r.objects){const [x,y,x2,y2]=o.box;ctx.strokeStyle=o.label==='person'?'#22C55E':'#00C2FF';ctx.fillStyle=ctx.strokeStyle;ctx.strokeRect(x*xScale,y*yScale,(x2-x)*xScale,(y2-y)*yScale);ctx.fillText(`${o.label} ${Math.round(o.confidence*100)}%`,x*xScale,Math.max(22,y*yScale-6));}
      $('#cameraStats').textContent=`${r.objects.length} obyekt · model ${r.latency_ms} ms · kamera ${v.videoWidth}×${v.videoHeight}`;
    }else $('#cameraStats').textContent='Kamera yoqilgan · avtomatik tahlil o‘chirilgan';
  }catch(e){if(e.name!=='AbortError')$('#cameraStats').textContent=e.message;}
  if(epoch===cameraEpoch&&cameraStream)cameraTimer=setTimeout(()=>cameraLoop(epoch),300);
}

let specificationData=null,annotationRows=[],reviewVideoId=null;
async function spec(){if(!specificationData)specificationData=await api('/api/specification');return specificationData;}
async function openReview(){
  if(!selected){$('#reviewTitle').textContent='Avval Tahlil bo‘limida video tanlang.';return;}
  await spec();$('#reviewTitle').textContent=selected.name;const id=selected.id;
  if(reviewVideoId!==id){const a=await api(`/api/videos/${id}/annotations`);reviewVideoId=id;annotationRows=a.events;$('#reviewed').checked=a.reviewed;$('#reviewVideo').src=`/api/videos/${id}/media`;$('#reviewStatus').textContent='';$('#reviewScore').classList.add('hidden');}
  $('#reviewEnd').max=selected.duration;renderAnnotations();boundaryHelp();
}
function boundaryHelp(){const d=specificationData?.events.find(d=>d.label===$('#reviewClass').value);if(d)$('#boundaryHelp').textContent=`Boshlanish: ${d.start}. Tugash: ${d.end}.`;}
$('#reviewClass').onchange=boundaryHelp;
$('#markStart').onclick=()=>$('#reviewStart').value=$('#reviewVideo').currentTime.toFixed(3);
$('#markEnd').onclick=()=>$('#reviewEnd').value=Math.min($('#reviewVideo').currentTime,selected?.duration||0).toFixed(3);
$('#frameBack').onclick=()=>{const v=$('#reviewVideo');v.pause();v.currentTime=Math.max(0,v.currentTime-1/(selected?.fps||30));};
$('#frameNext').onclick=()=>{const v=$('#reviewVideo');v.pause();v.currentTime=Math.min(selected?.duration||0,v.currentTime+1/(selected?.fps||30));};
function renderAnnotations(){
  $('#reviewRows').innerHTML=annotationRows.length?annotationRows.map((r,i)=>`<div class="review-item"><button data-review-seek="${r[0]}">${r[0].toFixed(3)}–${r[1].toFixed(3)} s</button><span>${esc(labels[r[2]])}</span><button data-review-delete="${i}" aria-label="Hodisani o‘chirish">O‘chirish</button></div>`).join(''):'<p class="muted">Hozircha qo‘lda belgilangan hodisa yo‘q.</p>';
  document.querySelectorAll('[data-review-seek]').forEach(b=>b.onclick=()=>{$('#reviewVideo').currentTime=Number(b.dataset.reviewSeek);});
  document.querySelectorAll('[data-review-delete]').forEach(b=>b.onclick=()=>{annotationRows.splice(Number(b.dataset.reviewDelete),1);$('#reviewed').checked=false;$('#reviewStatus').textContent='Saqlanmagan o‘zgarish';renderAnnotations();});
}
$('#addAnnotation').onclick=()=>{if(!selected||reviewVideoId!==selected.id)return toast('Avval video tanlang.',true);const s=Number($('#reviewStart').value),e=Number($('#reviewEnd').value);if(!Number.isFinite(s)||!Number.isFinite(e)||s<0||s>=e||e>selected.duration)return toast('Boshlanish va tugash video davomiyligi ichida bo‘lsin.',true);annotationRows.push([s,e,$('#reviewClass').value]);annotationRows.sort((a,b)=>a[0]-b[0]);$('#reviewed').checked=false;$('#reviewStatus').textContent='Saqlanmagan o‘zgarish';renderAnnotations();};
async function persistAnnotations(){if(!reviewVideoId)throw Error('Avval video tanlang.');const a=await api(`/api/videos/${reviewVideoId}/annotations`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({events:annotationRows,reviewed:$('#reviewed').checked})});annotationRows=a.events;renderAnnotations();$('#reviewStatus').textContent='Annotatsiya saqlandi.';}
$('#saveAnnotations').onclick=()=>persistAnnotations().catch(e=>toast(e.message,true));
$('#exportAnnotations').onclick=async()=>{try{await persistAnnotations();downloadObject(await api(`/api/videos/${reviewVideoId}/ground-truth`),'ground_truth.json');}catch(e){toast(e.message,true);}};
$('#scoreAnnotations').onclick=async()=>{try{await persistAnnotations();const jobs=await api('/api/jobs'),j=jobs.find(j=>j.video_id===reviewVideoId&&j.status==='done');if(!j)throw Error('Bu video uchun tugagan model tahlili kerak.');const d=await api(`/api/jobs/${j.id}/score/review`);$('#reviewScore').textContent=`${d.scope}\nPart A: ${d.report.part_a.score_a.toFixed(4)}\nPart B: ${d.report.part_b?d.report.part_b.score_b.toFixed(4):'accident yo‘q — baholanmaydi'}\nModel: ${d.report.model_score.toFixed(4)}\n\n`+JSON.stringify(d.report.part_a.per_class,null,2);$('#reviewScore').classList.remove('hidden');}catch(e){toast(e.message,true);}};

async function openProject(){
  const [s,p]=await Promise.all([spec(),api('/api/project')]);
  $('#specRows').innerHTML=s.events.map(d=>`<tr><td>${esc(d.name)}<br><small class="muted">${d.label}</small></td><td>${esc(d.start)}</td><td>${esc(d.end)}</td><td>${d.automatic?'Dastlabki sahna qoidasi':'Avtomatik detektor yo‘q; qo‘lda ko‘rish'}</td></tr>`).join('');
  $('#cameraDocState').textContent=s.camera_description_available?'samples/camera.md mavjud.':'samples/camera.md berilmagan. Chiziqlar, signal va taqiqlar uchun rasmiy kamera tavsifi hali kerak.';
  for(const [id,key] of [['projectTeam','team'],['projectRepo','repository'],['projectRevision','revision'],['projectWebsite','website'],['projectWeights','weights_url']])$('#'+id).value=p[key]||'';
  renderTeam(p);$('#saveProject').disabled=p.editable===false;$('#projectStatus').textContent=p.editable===false?'Public ko‘rinish. Ma’lumotlar repository orqali yangilanadi.':'';
  $('#memberForms').innerHTML=Array.from({length:3},(_,i)=>{const m=p.members[i]||{};return `<div class="member-form"><label>${i+1}-a’zo ismi<input type="text" data-member="${i}" data-field="name" value="${esc(m.name||'')}"></label><label>Vazifasi<input type="text" data-member="${i}" data-field="role" value="${esc(m.role||'')}"></label><label>Email<input type="email" data-member="${i}" data-field="email" value="${esc(m.email||'')}"></label><label>Portfolio havolasi<input type="text" data-member="${i}" data-field="portfolio" value="${esc(m.portfolio||'')}"></label></div>`;}).join('');
  const vs=await api('/api/videos');$('#sampleGallery').innerHTML=vs.filter(v=>v.source==='provided_sample'||v.source==='provided_sample_excerpt').map(v=>`<article class="panel sample-card"><img src="/api/videos/${v.id}/poster" alt="${esc(v.name)} kamera kadri"><h3>${esc(v.name)}</h3><small>${time(v.duration)} · ${v.width}×${v.height}<br>${v.source==='provided_sample_excerpt'?'Asl videodan qisqa parcha':'Berilgan to‘liq video'}</small><button class="text-button" data-sample="${v.id}">Videoni ochish →</button></article>`).join('')||'<p class="muted">Haqiqiy videolar yuklangach shu yerda ko‘rinadi.</p>';
  document.querySelectorAll('[data-sample]').forEach(b=>b.onclick=()=>{videos=vs;selectVideo(vs.find(v=>v.id===b.dataset.sample));page('analysis');});
}
$('#saveProject').onclick=async()=>{try{const p={team:$('#projectTeam').value,repository:$('#projectRepo').value,revision:$('#projectRevision').value,website:$('#projectWebsite').value,weights_url:$('#projectWeights').value,members:Array.from({length:3},(_,i)=>Object.fromEntries(['name','role','email','portfolio'].map(k=>[k,$(`[data-member="${i}"][data-field="${k}"]`).value])))};const saved=await api('/api/project',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)});renderTeam(saved);$('#team').value=saved.team;$('#projectStatus').textContent='Saqlandi.';}catch(e){toast(e.message,true);}};

function renderTeam(p){$('#teamCards').innerHTML=(p.members||[]).map(m=>`<article class="panel team-card"><span class="eyebrow">YUKSAVA TEAM</span><h2>${esc(m.name)}</h2><p>${esc(m.role)}</p>${m.email?`<a href="mailto:${esc(m.email)}">${esc(m.email)}</a>`:''}</article>`).join('');}

if(location.hash==='#project'){page('project');openProject().catch(e=>toast(e.message,true));}
